#### Numpy
- 파이썬 리스트: 속도가 느림, 메모리를 많이 차지
- 넘파이의 array(배열): 속도가 빠름, 메모리를 적게 차지, 모든 원소가 반드시 같은 자료형이어야 함. 원소의 개수를 바꿀 수 없음

###### 1) Numpy정의
- 수치 연산 패키지, 선형대수(벡터, 행렬)연산
- 벡터화 연산을 지원 -> 연산 속도가 빠름, 코드도 간단
- 선형대수는 데이터를 다루는 방법을 표현한 수식, 데이터 분해, 데이터 분석 기초

###### 2) 선형대수
- 행렬의 곱셈을 이용하여 데이터를 조작
- 역행렬을 이용한 회귀분석에 활용

In [13]:
import numpy as np
# 리스트를 넣으면 넘파이 배열을 만들어주는 함수
ar=np.array([0,1,2,3]) 
ar

# 0,1 int / 2.5 float, 정수 -> 실수로 자동 형변환
ar2=np.array([0,1,2.5]) 
ar2

# 숫자, 문자 -> 모두 문자로 자동 형변환
ar3=np.array([0,'a',1]) 
ar3

# 정수, 불린, 실수, 문자 -> 문자
ar4=np.array([0,'a',1,True,3.14]) 
ar4

# 정수, 불린, 실수 -> 실수로 자동 형변환
ar5=np.array([0,1,True,3.14])
ar5

# 정수, 불린 -> 정수로 자동 형변환
ar6=np.array([0,1,True])
ar6

array([0, 1, 1])

In [14]:
type(ar)
# numpy.ndarray -> n차원의 array

numpy.ndarray

* 벡터와 연산: 배열의 각 요소에 대한 반복 연산을 하나의 명령어로 빠르게 처리할 수 있도록 하는 기법

In [28]:
data=list(range(0,10))
data

# data 배열의 값을 2배씩해서 answer로 출력
answer=[]
for d in data:
    answer.append(d*2)
    
answer


[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [26]:
# 넘파이 2배 연산 / 벡터화 연산
x=np.array(data)
x*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [29]:
print(data*2) #data리스트를 2번 출력
print("="*50)
print(x*2)#x 배열의 각 요소값을 2배 해라

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [42]:
a=np.array([1,2,3])
b=np.array([10,20,30])
2*a+b
a==2 #각 요소가 2와 같은지 확인함
b>10
(a==2) & (b>10) # a가 2와 같으면서 b가 10보다 큰가
#True & True => True, 제외하고는 모두 False

array([False,  True, False])

In [37]:
a2=[1,2,3]
b2=[4,5,6]
a2*2+b2 #리스트에서는 *가 반복, +가 이어서(붙여서) 연결
a2==2 # a2는 2처럼 안생김. 리스트 자체로 비교해야함

False

In [51]:
# 0차원 array(배열) : 스칼라
# 1차원 array(배열) : 벡터
# 2차원 array(배열) : 행렬

c1= np.array([0,1,2]) #1차원
print(c1)

c2= np.array([[0,1,2],[3,4,5]]) #2차원 배열(행렬), 2*3 배열
print(c2)
len(c2) #행의 개수
c2[0] #첫번째 행 출력
len(c2[0]) #열의 개수


[0 1 2]
[[0 1 2]
 [3 4 5]]


3

In [59]:
d=np.array(list(range(1,25)))
d
d.reshape(6,4) #행6 열4

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [60]:
d=d.reshape(2,3,4) #2행 3열 깊이 4
d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [61]:
len(d) #행

2

In [63]:
len(d[0]) #열

3

In [64]:
len(d[0][0]) 
#3차원 배열의 행, 열, 깊이

4

In [66]:
a=np.array([1,2,3])
print(a.ndim) #ndim:차원
a.shape #shape:배열의 크기

1


(3,)

In [70]:
c=np.array([[0,1,2],[3,4,5]])
print(c.ndim)
print(c.shape)

2
(2, 3)


In [72]:
d.ndim
d.shape

(2, 3, 4)

In [73]:
a=np.array([0,1,2,3,4])
a[2] #2번 인덱스
a[-1] #마지막 1번째 인덱스

4

In [81]:
c=np.array([[0,1,2],[3,4,5]])
c[0,1]
c[1,2]
c[-1] #마지막 행을 의미
c[-1,-1] #마지막 행의 마지막 열 c[1,2]와 같음

5

In [84]:
c[: ,1 ] 
c[1, 1:] #2번째 행의 2번째 열부터 마지막 열까지

array([4, 5])

In [86]:
c[:1, ] #0번 행만 추출 1은 미포함
c[:1,:1] #0번 행,0번 열
c[:1,:2] #0번 인덱스 행, 0번~2~1번 인덱스 열 추출

array([[0]])

In [92]:
a=np.array([0,1,2,3])
idx=np.array([True,False,True,False]) #길이가 같아야 함
a[idx] #index error가 발생할 수 있으므로 주의 (크기 동일) / 트루에 해당하는 값만 추출
a%2 #array([0, 1, 0, 1], dtype=int32)
a%2==0  #array([ True, False,  True, False])
a[a%2==0 ] #array([0, 2]) True에 해당하는 값만 추출

array([0, 2])

In [94]:
a=np.array([10,20,30,40,50])
idx=np.array([0,2,4])
a[idx] #0번, 2번, 4번째 값이 출력됨

array([10, 30, 50])

In [112]:
m = np.array([[0,1,2,3,4], 
              [5,6,7,8,9],
             [10,11,12,13,14]])
# 이 행렬에서 값 7을 인덱싱한다
m[1,2] #-2,2 / -2,-3

# 이 행렬에서 값 14을 인덱싱한다
m[-1,-1]

# 이 행렬에서 배열 [6,7]을 슬라이싱한다
m[1,1:3]

# 이 행렬에서 값 [7,12]을 슬라이싱한다
m[1:,2]

# 이 행렬에서 값 [[3,4],[8,9]]을 슬라이싱한다
m[:2, 3:]

array([[3, 4],
       [8, 9]])

In [123]:
a=np.array(list(range(1,13)))
a
a=a.reshape(3,4)

In [124]:
a[:,[True, False, False, True]]

array([[ 1,  4],
       [ 5,  8],
       [ 9, 12]])

In [125]:
a[[True, False, True] ,:]

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [127]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [126]:
a[[2,0,1],:]

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [136]:
# [ ]안에 있는 값을 자동으로 지정해준다

x=np.array([1,2,3])
x.dtype #int32

x=np.array([1.1,2.1,3.1])
x.dtype #float64 #x변수에 저장된 데이터의 타입
type(x) # x 라는 변수의 타입이 무엇이냐?(자료구조)

x=np.array([1,2,3.14])
x.dtype #dtype('float64')
x
#dtype을 명시하지 않으면 넘파이에서 내부적으로 추정하여 데이터를 저장
#dtype을 명시하면, 명시된 타입으로 변환하여 저장


array([1.  , 2.  , 3.14])

In [135]:
x=np.array([1,2,3], dtype=float)
x.dtype #int32 -> float64

dtype('float64')

In [137]:
x[0]+x[1] #요소간의 덧셈가능

3.0

In [140]:
x=np.array([0,1,-1,0])
y=np.array([1,0,0,0])
x/y # array([  0.,  inf, -inf,  nan]) = (0, 무한대(양), 무한대(음), nan:정의할 수 없는 숫자(not a number))

C:\Users\B-7\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\B-7\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until


array([  0.,  inf, -inf,  nan])

In [141]:
np.log(0) #-inf

C:\Users\B-7\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


-inf

In [145]:
x=np.zeros(3)
x 
#array([0., 0., 0.]) : 0으로 채워주는 함수

array([0., 0., 0.])

In [147]:
x=np.zeros((2,3)) #튜플 형태로 크기를 정의하여 다차원 배열을 나타냄
x  #기본값 float
#array([0., 0., 0.]) : 2차원을 0으로 채워주는 함수

array([[0., 0., 0.],
       [0., 0., 0.]])

In [166]:
x=np.zeros((2,3), dtype="i") 
x 
x.dtype
#int 지정

dtype('int32')

In [167]:
x

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [168]:
y=np.zeros_like(x)
y

#x와 같은 구조로 y를 만들되, 0으로 초기화하여 y에 저장 (2행 3열)

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [169]:
x=np.ones((2,3,4)) #2행 3열 4깊이
x

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [170]:
z=np.ones_like(y)  #어떤 구조와 동일하게 해서 채울 것인가? y와 동일한 구조에 값을 1로 채운다
z

array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [171]:
z2=z*2
z2

array([[2, 2, 2],
       [2, 2, 2]], dtype=int32)

In [173]:
# range:파이썬, arange:넘파이
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [175]:
np.arange(2,11,3) #11은 포함 안함

array([2, 5, 8])

In [176]:
np.linspace(0,100,5) #선형 구간을 5개로 분할

array([  0.,  25.,  50.,  75., 100.])

In [177]:
a=np.array([[1,2,3],[4,5,6]])
a.T #transpose: 전치행렬

array([[1, 4],
       [2, 5],
       [3, 6]])

In [184]:
# a=np.arange(12) 
# a=np.array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
a=np.array(list(range(0,12)))
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [191]:
a.reshape(3,4)
a.reshape(3,-1) # -1은 니가 알아서 계산해! 행만 3개로 하면 돼~
a.reshape(2,2,-1)# 경우의 수가 많기 때문에 마지막 한개만 -1을 지정하여 계산을 맡길 수 있음

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [192]:
a=a.reshape(2,-1,2)
a.shape

#1차원 데이터를 다른 차원으로 변환할 때는 reshape함수를 쓴다

(2, 3, 2)

In [193]:
#flatten, ravel: 다른(n) 차원을 1차원으로 변환하는 함수
a.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [195]:
a.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [196]:
x=np.arange(5)
x

array([0, 1, 2, 3, 4])

In [206]:
x=x.reshape(1,5) #array([[0, 1, 2, 3, 4]]): 1행 5열 : 대괄호가 2개 열렸기때문에 2차원임
x.flatten() # 2 -> 1차원
x.shape

(1, 5)

In [207]:
x=x.reshape(5,1)# 행렬의 위치가 다르기 때문에 (1,5)와 (5,1)은 다르다
x.shape

(5, 1)

In [216]:
x=np.arange(5)
x=x[:, np.newaxis] #newaxis: 배열에 대해 차원을 1만큼 증가
x
x.shape

(5, 1)

In [217]:
# hstack: 행의 수가 같은 배열을 옆으로 연결(열이 증가)
x1=np.ones((2,3))
x1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [220]:
x2=np.zeros((2,2))
x2

array([[0., 0.],
       [0., 0.]])

In [225]:
# np.hstack([x2,x1]) #x2를 기준으로 우측에 x1이 연결
# np.hstack([x1,x2]) #x1를 기준으로 우측에 x2이 연결
x3=np.zeros((2,2))
x3

array([[0., 0.],
       [0., 0.]])

In [231]:
# np.hstack([x,x3])

In [230]:
y1=np.ones((2,3))
y2=np.zeros((3,3))
np.vstack([y1,y2])

array([[1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])