In [3]:
import numpy as np

In [8]:
# 연습문제
# 1) 다음 행렬과 같은 배열이 있다.
x = np.array([1,2,3,4,5,6,7,8,9,10,
              11,12,13,14,15,16,17,18,19,20])
# 이 배열에서 3의 배수를 찾아라.
x[x%3==0]

# 이 배열에서 4로 나누면 1이 남는 수를 찾아라.
x[x%4==1]

# 이 배열에서 3으로 나누면 나누어지고 4로 나누면 1이 남는 수를 찾아라.
x[(x%3==0) & (x%4==1)]


array([9])

In [39]:
# 2) 타이타닉, 데이터(data.go.kr)로 오늘 학습한 내용들을 연습
import pandas as pd
stock=pd.read_csv("data/000120.KS.csv")

In [40]:
stock.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 197 entries, 0 to 196
Data columns (total 6 columns):
Open         197 non-null int64
High         197 non-null int64
Low          197 non-null int64
Close        197 non-null int64
Adj_Close    197 non-null int64
Volume       197 non-null int64
dtypes: int64(6)
memory usage: 9.3 KB


In [42]:
stock_h=stock.head()
stock_h

Open    High     Low   Close  Adj_Close  Volume
0  144000  147000  142500  145000     145000  109794
1  144500  148000  144000  146500     146500  120082
2  148500  151500  146500  149500     149500  133603
3  150000  151500  145000  150500     150500   97546
4  151500  155500  148000  155000     155000  131724

In [43]:
stock_t=stock.tail()
stock_t

Open    High     Low   Close  Adj_Close  Volume
192  167500  168500  166000  168000     168000   43412
193  168500  170000  165000  166500     166500   62176
194  168000  169000  165500  168000     168000   62318
195  168000  169000  164500  164500     164500   76594
196  167500  180000  165500  176500     176500  202777

In [49]:
stock_h=np.array(stock_h)
stock1=stock_h.reshape(5,6)
stock1

array([[144000, 147000, 142500, 145000, 145000, 109794],
       [144500, 148000, 144000, 146500, 146500, 120082],
       [148500, 151500, 146500, 149500, 149500, 133603],
       [150000, 151500, 145000, 150500, 150500,  97546],
       [151500, 155500, 148000, 155000, 155000, 131724]], dtype=int64)

In [65]:
stock_t=np.array(stock_t)
stock2=stock_t.reshape(5,-1)
stock2

array([[167500, 168500, 166000, 168000, 168000,  43412],
       [168500, 170000, 165000, 166500, 166500,  62176],
       [168000, 169000, 165500, 168000, 168000,  62318],
       [168000, 169000, 164500, 164500, 164500,  76594],
       [167500, 180000, 165500, 176500, 176500, 202777]], dtype=int64)

In [68]:
#합계
# stock1+stock2

In [72]:
# [202777] 뽑기
stock2[-1,-1]

# [166500,  62176]
stock2[1,-2:]

# [164500, 164500, 164500,  76594]
stock2[-2,-4:]

array([164500, 164500, 164500,  76594], dtype=int64)

0, 1 연습

In [54]:
a=np.zeros((3,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [55]:
b=np.ones((2,4))
b

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [58]:
c=np.zeros_like(b)
c

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [59]:
np.vstack([b,a])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

테슬라



In [82]:
tesla=pd.read_csv("data/TSLA.csv", parse_dates=["Date"])
tesla.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1259 entries, 0 to 1258
Data columns (total 7 columns):
Date         1259 non-null datetime64[ns]
Open         1259 non-null float64
High         1259 non-null float64
Low          1259 non-null float64
Close        1259 non-null float64
Adj Close    1259 non-null float64
Volume       1259 non-null int64
dtypes: datetime64[ns](1), float64(5), int64(1)
memory usage: 68.9 KB


In [83]:
# 인덱스 데이트로 바꾸기
tesla.index=tesla['Date']

In [84]:
tesla

Date        Open        High         Low       Close  \
Date                                                                    
2014-04-15 2014-04-15  199.089996  199.289993  184.320007  193.910004   
2014-04-16 2014-04-16  197.000000  199.990005  190.820007  199.110001   
2014-04-17 2014-04-17  199.610001  202.289993  194.080002  198.119995   
2014-04-21 2014-04-21  197.080002  206.199997  194.000000  204.380005   
2014-04-22 2014-04-22  206.360001  219.330002  205.009995  218.639999   
2014-04-23 2014-04-23  216.330002  216.740005  207.000000  207.990005   
2014-04-24 2014-04-24  210.809998  212.800003  203.199997  207.860001   
2014-04-25 2014-04-25  202.000000  206.699997  197.649994  199.850006   
2014-04-28 2014-04-28  200.000000  203.789993  190.500000  198.509995   
2014-04-29 2014-04-29  198.210007  207.149994  195.529999  206.919998   
2014-04-30 2014-04-30  203.600006  208.160004  201.279999  207.889999   
2014-05-01 2014-05-01  207.080002  214.020004  205.690002  207.729996   
2014-05-02 2014-05-02  208.600006  211.360001  206.520004  210.910004   
2014-05-05 2014-05-05  209.479996  217.690002  208.520004  216.610001   
2014-05-06 2014-05-06  216.600006  218.660004  206.850006  207.279999   
2014-05-07 2014-05-07  209.639999  210.199997  197.250000  201.350006   
2014-05-08 2014-05-08  182.000000  194.399994  178.000000  178.589996   
2014-05-09 2014-05-09  179.860001  183.399994  177.220001  182.259995   
2014-05-12 2014-05-12  183.869995  187.190002  179.880005  184.669998   
2014-05-13 2014-05-13  183.759995  191.339996  183.000000  190.160004   
2014-05-14 2014-05-14  188.949997  193.479996  187.100006  190.619995   
2014-05-15 2014-05-15  189.979996  192.660004  185.300003  188.589996   
2014-05-16 2014-05-16  188.949997  192.039993  187.720001  191.559998   
2014-05-19 2014-05-19  190.720001  196.889999  190.000000  196.089996   
2014-05-20 2014-05-20  196.940002  199.330002  193.070007  195.300003   
2014-05-21 2014-05-21  196.179993  199.869995  194.789993  199.449997   
2014-05-22 2014-05-22  200.350006  206.880005  199.559998  204.880005   
2014-05-23 2014-05-23  204.529999  207.759995  202.500000  207.300003   
2014-05-27 2014-05-27  208.520004  213.869995  207.699997  211.559998   
2014-05-28 2014-05-28  210.020004  212.770004  205.259995  210.240005   
...               ...         ...         ...         ...         ...   
2019-03-05 2019-03-05  282.000000  284.000000  270.100006  276.540009   
2019-03-06 2019-03-06  276.480011  281.510010  274.390015  276.239990   
2019-03-07 2019-03-07  278.839996  284.700012  274.250000  276.589996   
2019-03-08 2019-03-08  276.910004  285.589996  275.890015  284.140015   
2019-03-11 2019-03-11  283.519989  291.279999  280.500000  290.920013   
2019-03-12 2019-03-12  286.489990  288.070007  281.059998  283.359985   
2019-03-13 2019-03-13  283.899994  291.989990  282.700012  288.959991   
2019-03-14 2019-03-14  292.450012  295.390015  288.290009  289.959991   
2019-03-15 2019-03-15  283.510010  283.720001  274.399994  275.429993   
2019-03-18 2019-03-18  276.000000  278.049988  267.299988  269.489990   
2019-03-19 2019-03-19  267.500000  273.299988  263.459991  267.470001   
2019-03-20 2019-03-20  269.690002  274.970001  266.299988  273.600006   
2019-03-21 2019-03-21  272.600006  276.450012  268.450012  274.019989   
2019-03-22 2019-03-22  272.579987  272.799988  264.000000  264.529999   
2019-03-25 2019-03-25  259.709991  263.179993  254.460007  260.420013   
2019-03-26 2019-03-26  264.440002  270.260010  264.429993  267.769989   
2019-03-27 2019-03-27  268.750000  275.369995  268.179993  274.829987   
2019-03-28 2019-03-28  277.160004  280.329987  275.100006  278.619995   
2019-03-29 2019-03-29  278.700012  280.160004  274.500000  279.859985   
2019-04-01 2019-04-01  282.619995  289.200012  281.279999  289.179993   
2019-04-02 2019-04-02  288.299988  289.440002  283.880005  285.880005   
2019-04-03 2019-04-03  287.320007  296.170013  287.170013  291.809998   
20